### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by diedvdyk** [rappenze/pyfibaro#10]
Feature request:

The Fibaro HC2 and HC3 servers support https with a signed certificate from Fibaro.
Can you add https support (with no SSL verification) in this library and later on in the Home Assistant Fibaro Integration ?

**Comment by rappenze** [comment]
Fibaro Home Center 3 uses a root certificate authority, two intermediate certificate authorities and a per device certificate. The per device certificate changes each month. I didn't find anything to upload an own certificate.

So there are two options:
- Set verify to False which exposes the requests to man-in-the-middle attacks but is easy to do. Also this solution will log InsecureRequestWarning on each request until this is globally disabled in urllib3 library (disabling it per host is not possible). So I'm unsure if Home Assistant will accept such a solution and if such warnings in HA are already disabled.
- Implement certificate validation by fingerprint. This is more secure but you need to provide the monthly changing fingerprint.

What do you think should be implemented in the library, both options? And which solution should be used in HA?

I will try to find out how the maintainer of HA think it should be done.

**Comment by diedvdyk** [comment]
The integration Overkiz uses verify to flalse too with access to the Tahoma device. So there is a precedent for this.

**Comment by rappenze** [comment]
Ok thanks, I also checked messages on HA discord channel and it seems that this option is widely used. So I will implement the ssl verify = False option.

**Comment by rappenze** [comment]
This is integrated in Home Assistant 2023.3.0, so you should soon be able to use https as well in Home Assistant.

**Comment by diedvdyk** [comment]
I have installed 2023.3.0 but the dialog hint still says http://HOST/api/* . Before I migrate my 89 devices to https I have to be sure the https is accepted in the dialog of the intergration. Is it ?

**Comment by rappenze** [comment]
Yes https is now accepted, also in HA there is now some url fixing setup so even entering https://HOST works now. But yes the dialog text is not good anymore, I will update it if I find some time.

**Comment by diedvdyk** [comment]
I have done the migration to https with success.
