### ISSUE TITLE
Allow passing optional `Fibaro-User-PIN` header to scenes

### ISSUE THREAD

**Issue by mmiszy** [rappenze/pyfibaro#23]
Allow passing optional `Fibaro-User-PIN` header to scenes that require one.

**Comment by rappenze** [comment]
Thanks for the request. Should be easy to be implemented for HC3.

The url we are currently using is `/api/scenes/#/execute`. So why do you think that the url should be different?

What do you suggest to do for HC2? Do you know if it is also supported there?

**Comment by rappenze** [comment]
Available starting with release 0.7.3.
